//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DHL_SCEntities : DbContext
    {
        public DHL_SCEntities()
            : base("name=DHL_SCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<sp_WebAppSeguimientoConsDatos_Result> sp_WebAppSeguimientoConsDatos(Nullable<int> opc, string cve_filtro_1, string cve_filtro_2)
        {
            var opcParameter = opc.HasValue ?
                new ObjectParameter("opc", opc) :
                new ObjectParameter("opc", typeof(int));
    
            var cve_filtro_1Parameter = cve_filtro_1 != null ?
                new ObjectParameter("cve_filtro_1", cve_filtro_1) :
                new ObjectParameter("cve_filtro_1", typeof(string));
    
            var cve_filtro_2Parameter = cve_filtro_2 != null ?
                new ObjectParameter("cve_filtro_2", cve_filtro_2) :
                new ObjectParameter("cve_filtro_2", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_WebAppSeguimientoConsDatos_Result>("sp_WebAppSeguimientoConsDatos", opcParameter, cve_filtro_1Parameter, cve_filtro_2Parameter);
        }
    
        public virtual ObjectResult<sp_WebAppAdmSeguimiento_Result> sp_WebAppAdmSeguimiento(Nullable<int> id, string cv, string ruta, string proveedor, string placas, string carrier, string tip_unidad, string operador, Nullable<System.DateTime> fec_recoleccion, string alm_descarga, string status, Nullable<System.DateTime> fec_llegadaRealProv, Nullable<System.DateTime> fec_entradaRealProv, string llegada_otdProv, Nullable<System.TimeSpan> llegada_delayProv, string llegada_justiProv, string llegada_comenProv, Nullable<System.DateTime> fec_salidaRealProv, string salida_otdProv, Nullable<System.TimeSpan> salida_delayProv, string salida_justiProv, string salida_comenProv, Nullable<System.DateTime> fec_llegadaRealMonde, Nullable<System.DateTime> fec_entradaRealMonde, string llegada_otdMonde, Nullable<System.TimeSpan> llegada_delayMonde, string llegada_justiMonde, string llegada_comenMonde, Nullable<System.DateTime> fec_salidaRealMonde, string salida_otdMonde, Nullable<System.TimeSpan> salida_delayMonde, string salida_justiMonde, string salida_comenMonde, Nullable<System.DateTime> fec_salidaProgProv, Nullable<System.DateTime> fec_salidaProgMonde, Nullable<System.TimeSpan> estadiaProv, Nullable<System.TimeSpan> estadiaMonde, Nullable<System.DateTime> fec_progMonde, Nullable<int> opc)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var cvParameter = cv != null ?
                new ObjectParameter("cv", cv) :
                new ObjectParameter("cv", typeof(string));
    
            var rutaParameter = ruta != null ?
                new ObjectParameter("ruta", ruta) :
                new ObjectParameter("ruta", typeof(string));
    
            var proveedorParameter = proveedor != null ?
                new ObjectParameter("proveedor", proveedor) :
                new ObjectParameter("proveedor", typeof(string));
    
            var placasParameter = placas != null ?
                new ObjectParameter("placas", placas) :
                new ObjectParameter("placas", typeof(string));
    
            var carrierParameter = carrier != null ?
                new ObjectParameter("carrier", carrier) :
                new ObjectParameter("carrier", typeof(string));
    
            var tip_unidadParameter = tip_unidad != null ?
                new ObjectParameter("tip_unidad", tip_unidad) :
                new ObjectParameter("tip_unidad", typeof(string));
    
            var operadorParameter = operador != null ?
                new ObjectParameter("operador", operador) :
                new ObjectParameter("operador", typeof(string));
    
            var fec_recoleccionParameter = fec_recoleccion.HasValue ?
                new ObjectParameter("fec_recoleccion", fec_recoleccion) :
                new ObjectParameter("fec_recoleccion", typeof(System.DateTime));
    
            var alm_descargaParameter = alm_descarga != null ?
                new ObjectParameter("alm_descarga", alm_descarga) :
                new ObjectParameter("alm_descarga", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(string));
    
            var fec_llegadaRealProvParameter = fec_llegadaRealProv.HasValue ?
                new ObjectParameter("fec_llegadaRealProv", fec_llegadaRealProv) :
                new ObjectParameter("fec_llegadaRealProv", typeof(System.DateTime));
    
            var fec_entradaRealProvParameter = fec_entradaRealProv.HasValue ?
                new ObjectParameter("fec_entradaRealProv", fec_entradaRealProv) :
                new ObjectParameter("fec_entradaRealProv", typeof(System.DateTime));
    
            var llegada_otdProvParameter = llegada_otdProv != null ?
                new ObjectParameter("llegada_otdProv", llegada_otdProv) :
                new ObjectParameter("llegada_otdProv", typeof(string));
    
            var llegada_delayProvParameter = llegada_delayProv.HasValue ?
                new ObjectParameter("llegada_delayProv", llegada_delayProv) :
                new ObjectParameter("llegada_delayProv", typeof(System.TimeSpan));
    
            var llegada_justiProvParameter = llegada_justiProv != null ?
                new ObjectParameter("llegada_justiProv", llegada_justiProv) :
                new ObjectParameter("llegada_justiProv", typeof(string));
    
            var llegada_comenProvParameter = llegada_comenProv != null ?
                new ObjectParameter("llegada_comenProv", llegada_comenProv) :
                new ObjectParameter("llegada_comenProv", typeof(string));
    
            var fec_salidaRealProvParameter = fec_salidaRealProv.HasValue ?
                new ObjectParameter("fec_salidaRealProv", fec_salidaRealProv) :
                new ObjectParameter("fec_salidaRealProv", typeof(System.DateTime));
    
            var salida_otdProvParameter = salida_otdProv != null ?
                new ObjectParameter("salida_otdProv", salida_otdProv) :
                new ObjectParameter("salida_otdProv", typeof(string));
    
            var salida_delayProvParameter = salida_delayProv.HasValue ?
                new ObjectParameter("salida_delayProv", salida_delayProv) :
                new ObjectParameter("salida_delayProv", typeof(System.TimeSpan));
    
            var salida_justiProvParameter = salida_justiProv != null ?
                new ObjectParameter("salida_justiProv", salida_justiProv) :
                new ObjectParameter("salida_justiProv", typeof(string));
    
            var salida_comenProvParameter = salida_comenProv != null ?
                new ObjectParameter("salida_comenProv", salida_comenProv) :
                new ObjectParameter("salida_comenProv", typeof(string));
    
            var fec_llegadaRealMondeParameter = fec_llegadaRealMonde.HasValue ?
                new ObjectParameter("fec_llegadaRealMonde", fec_llegadaRealMonde) :
                new ObjectParameter("fec_llegadaRealMonde", typeof(System.DateTime));
    
            var fec_entradaRealMondeParameter = fec_entradaRealMonde.HasValue ?
                new ObjectParameter("fec_entradaRealMonde", fec_entradaRealMonde) :
                new ObjectParameter("fec_entradaRealMonde", typeof(System.DateTime));
    
            var llegada_otdMondeParameter = llegada_otdMonde != null ?
                new ObjectParameter("llegada_otdMonde", llegada_otdMonde) :
                new ObjectParameter("llegada_otdMonde", typeof(string));
    
            var llegada_delayMondeParameter = llegada_delayMonde.HasValue ?
                new ObjectParameter("llegada_delayMonde", llegada_delayMonde) :
                new ObjectParameter("llegada_delayMonde", typeof(System.TimeSpan));
    
            var llegada_justiMondeParameter = llegada_justiMonde != null ?
                new ObjectParameter("llegada_justiMonde", llegada_justiMonde) :
                new ObjectParameter("llegada_justiMonde", typeof(string));
    
            var llegada_comenMondeParameter = llegada_comenMonde != null ?
                new ObjectParameter("llegada_comenMonde", llegada_comenMonde) :
                new ObjectParameter("llegada_comenMonde", typeof(string));
    
            var fec_salidaRealMondeParameter = fec_salidaRealMonde.HasValue ?
                new ObjectParameter("fec_salidaRealMonde", fec_salidaRealMonde) :
                new ObjectParameter("fec_salidaRealMonde", typeof(System.DateTime));
    
            var salida_otdMondeParameter = salida_otdMonde != null ?
                new ObjectParameter("salida_otdMonde", salida_otdMonde) :
                new ObjectParameter("salida_otdMonde", typeof(string));
    
            var salida_delayMondeParameter = salida_delayMonde.HasValue ?
                new ObjectParameter("salida_delayMonde", salida_delayMonde) :
                new ObjectParameter("salida_delayMonde", typeof(System.TimeSpan));
    
            var salida_justiMondeParameter = salida_justiMonde != null ?
                new ObjectParameter("salida_justiMonde", salida_justiMonde) :
                new ObjectParameter("salida_justiMonde", typeof(string));
    
            var salida_comenMondeParameter = salida_comenMonde != null ?
                new ObjectParameter("salida_comenMonde", salida_comenMonde) :
                new ObjectParameter("salida_comenMonde", typeof(string));
    
            var fec_salidaProgProvParameter = fec_salidaProgProv.HasValue ?
                new ObjectParameter("fec_salidaProgProv", fec_salidaProgProv) :
                new ObjectParameter("fec_salidaProgProv", typeof(System.DateTime));
    
            var fec_salidaProgMondeParameter = fec_salidaProgMonde.HasValue ?
                new ObjectParameter("fec_salidaProgMonde", fec_salidaProgMonde) :
                new ObjectParameter("fec_salidaProgMonde", typeof(System.DateTime));
    
            var estadiaProvParameter = estadiaProv.HasValue ?
                new ObjectParameter("estadiaProv", estadiaProv) :
                new ObjectParameter("estadiaProv", typeof(System.TimeSpan));
    
            var estadiaMondeParameter = estadiaMonde.HasValue ?
                new ObjectParameter("estadiaMonde", estadiaMonde) :
                new ObjectParameter("estadiaMonde", typeof(System.TimeSpan));
    
            var fec_progMondeParameter = fec_progMonde.HasValue ?
                new ObjectParameter("fec_progMonde", fec_progMonde) :
                new ObjectParameter("fec_progMonde", typeof(System.DateTime));
    
            var opcParameter = opc.HasValue ?
                new ObjectParameter("opc", opc) :
                new ObjectParameter("opc", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_WebAppAdmSeguimiento_Result>("sp_WebAppAdmSeguimiento", idParameter, cvParameter, rutaParameter, proveedorParameter, placasParameter, carrierParameter, tip_unidadParameter, operadorParameter, fec_recoleccionParameter, alm_descargaParameter, statusParameter, fec_llegadaRealProvParameter, fec_entradaRealProvParameter, llegada_otdProvParameter, llegada_delayProvParameter, llegada_justiProvParameter, llegada_comenProvParameter, fec_salidaRealProvParameter, salida_otdProvParameter, salida_delayProvParameter, salida_justiProvParameter, salida_comenProvParameter, fec_llegadaRealMondeParameter, fec_entradaRealMondeParameter, llegada_otdMondeParameter, llegada_delayMondeParameter, llegada_justiMondeParameter, llegada_comenMondeParameter, fec_salidaRealMondeParameter, salida_otdMondeParameter, salida_delayMondeParameter, salida_justiMondeParameter, salida_comenMondeParameter, fec_salidaProgProvParameter, fec_salidaProgMondeParameter, estadiaProvParameter, estadiaMondeParameter, fec_progMondeParameter, opcParameter);
        }
    
        public virtual ObjectResult<sp_WebAppConsultaSeguimiento_Result> sp_WebAppConsultaSeguimiento(string filtro1, string filtro2, Nullable<int> opc)
        {
            var filtro1Parameter = filtro1 != null ?
                new ObjectParameter("filtro1", filtro1) :
                new ObjectParameter("filtro1", typeof(string));
    
            var filtro2Parameter = filtro2 != null ?
                new ObjectParameter("filtro2", filtro2) :
                new ObjectParameter("filtro2", typeof(string));
    
            var opcParameter = opc.HasValue ?
                new ObjectParameter("opc", opc) :
                new ObjectParameter("opc", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_WebAppConsultaSeguimiento_Result>("sp_WebAppConsultaSeguimiento", filtro1Parameter, filtro2Parameter, opcParameter);
        }
    }
}
